package Vistas.gui;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.text.JTextComponent;

public class VentanaPrincipal extends javax.swing.JFrame {

    public static FondoVisual background = new FondoVisual();

    public VentanaPrincipal() {
        this.setContentPane(background);
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        barraDeMenu = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        itemRecordarClaveUsuario = new javax.swing.JMenuItem();
        itemCambiarClaveUsuario = new javax.swing.JMenuItem();
        itemSalirUsuario = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        itemAgregarUsuario = new javax.swing.JMenuItem();
        itemBuscarUsuario = new javax.swing.JMenuItem();
        itemEditarUsuario = new javax.swing.JMenuItem();
        itemEliminarUsuario = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesUsuario = new javax.swing.JMenu();
        itemBuscarPorId1 = new javax.swing.JMenuItem();
        itemBuscarPorCodigoProyecto1 = new javax.swing.JMenuItem();
        menuEmpleado = new javax.swing.JMenu();
        itemAgregarEmpleado = new javax.swing.JMenuItem();
        itemBuscarEmpleado = new javax.swing.JMenuItem();
        itemEditarEmpleado = new javax.swing.JMenuItem();
        itemEliminarEmpleado = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesEmpleado = new javax.swing.JMenu();
        itemBuscarPorId2 = new javax.swing.JMenuItem();
        itemBuscarPorCodigoProyecto2 = new javax.swing.JMenuItem();
        menuEmpresa = new javax.swing.JMenu();
        itemAgregarEmpresa = new javax.swing.JMenuItem();
        itemBuscarEmpresa = new javax.swing.JMenuItem();
        itemEditarEmpresa = new javax.swing.JMenuItem();
        itemEliminarEmpresa = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesEmpresa = new javax.swing.JMenu();
        itemBuscarPorId3 = new javax.swing.JMenuItem();
        itemBuscarPorCodigoProyecto3 = new javax.swing.JMenuItem();
        menuPromotor = new javax.swing.JMenu();
        itemAgregarPromotor = new javax.swing.JMenuItem();
        itemBuscarPromotor = new javax.swing.JMenuItem();
        itemEditarPromotor = new javax.swing.JMenuItem();
        itemEliminarPromotor = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesPromotor = new javax.swing.JMenu();
        itemBuscarPorId4 = new javax.swing.JMenuItem();
        itemBuscarPorCodigoProyecto4 = new javax.swing.JMenuItem();
        menuProyecto = new javax.swing.JMenu();
        itemAgregarProyecto = new javax.swing.JMenuItem();
        itemBuscarProyecto = new javax.swing.JMenuItem();
        itemEditarProyecto = new javax.swing.JMenuItem();
        itemEliminarProyecto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesProyecto = new javax.swing.JMenu();
        itemBuscarPorId = new javax.swing.JMenuItem();
        itemBuscarPorCodigoProyecto = new javax.swing.JMenuItem();
        menuTarea = new javax.swing.JMenu();
        itemAgregarTarea = new javax.swing.JMenuItem();
        itemBuscarTarea = new javax.swing.JMenuItem();
        itemEditarTarea = new javax.swing.JMenuItem();
        itemEliminarTarea = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesTarea = new javax.swing.JMenu();
        itemBuscarPorId6 = new javax.swing.JMenuItem();
        itemBuscarPorCodigoProyecto6 = new javax.swing.JMenuItem();
        menuDocumento = new javax.swing.JMenu();
        itemAgregarDocumento = new javax.swing.JMenuItem();
        itemBuscarDocumento = new javax.swing.JMenuItem();
        itemEditarDocumento = new javax.swing.JMenuItem();
        itemEliminarDocumento = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesDocumento = new javax.swing.JMenu();
        itemBuscarPorId5 = new javax.swing.JMenuItem();
        itemBuscarPorCodigoProyecto5 = new javax.swing.JMenuItem();
        menuVersion = new javax.swing.JMenu();
        itemAgregarVersion = new javax.swing.JMenuItem();
        itemBuscarVersion = new javax.swing.JMenuItem();
        itemEditarVersion = new javax.swing.JMenuItem();
        itemEliminarVersion = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesVersion = new javax.swing.JMenu();
        itemBuscarPorId7 = new javax.swing.JMenuItem();
        itemBuscarPorCodigoProyecto7 = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("..::Gestión de Proyectos Empresariales::..");

        menuUsuario.setText("Usuario");
        menuUsuario.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jMenuItem1.setText("Iniciar Sesion");
        menuUsuario.add(jMenuItem1);

        itemRecordarClaveUsuario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemRecordarClaveUsuario.setText("Recordar Password");
        menuUsuario.add(itemRecordarClaveUsuario);

        itemCambiarClaveUsuario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemCambiarClaveUsuario.setText("Cambiar Password");
        menuUsuario.add(itemCambiarClaveUsuario);

        itemSalirUsuario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemSalirUsuario.setText("Salir");
        menuUsuario.add(itemSalirUsuario);
        menuUsuario.add(jSeparator9);

        itemAgregarUsuario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemAgregarUsuario.setText("Agregar...");
        itemAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(itemAgregarUsuario);

        itemBuscarUsuario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarUsuario.setText("Buscar...");
        itemBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(itemBuscarUsuario);

        itemEditarUsuario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemEditarUsuario.setText("Modificar...");
        itemEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(itemEditarUsuario);

        itemEliminarUsuario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemEliminarUsuario.setText("Eliminar...");
        itemEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(itemEliminarUsuario);
        menuUsuario.add(jSeparator2);

        subMenuReportesUsuario.setText("Reportes...");
        subMenuReportesUsuario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        itemBuscarPorId1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarPorId1.setText("Buscar por Id");
        subMenuReportesUsuario.add(itemBuscarPorId1);

        itemBuscarPorCodigoProyecto1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarPorCodigoProyecto1.setText("Buscar por Codigo Proyecto");
        subMenuReportesUsuario.add(itemBuscarPorCodigoProyecto1);

        menuUsuario.add(subMenuReportesUsuario);

        barraDeMenu.add(menuUsuario);

        menuEmpleado.setText("Empleado");
        menuEmpleado.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        itemAgregarEmpleado.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemAgregarEmpleado.setText("Agregar...");
        itemAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarEmpleadoActionPerformed(evt);
            }
        });
        menuEmpleado.add(itemAgregarEmpleado);

        itemBuscarEmpleado.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarEmpleado.setText("Buscar...");
        itemBuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarEmpleadoActionPerformed(evt);
            }
        });
        menuEmpleado.add(itemBuscarEmpleado);

        itemEditarEmpleado.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemEditarEmpleado.setText("Modificar...");
        itemEditarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarEmpleadoActionPerformed(evt);
            }
        });
        menuEmpleado.add(itemEditarEmpleado);

        itemEliminarEmpleado.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemEliminarEmpleado.setText("Eliminar...");
        itemEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarEmpleadoActionPerformed(evt);
            }
        });
        menuEmpleado.add(itemEliminarEmpleado);
        menuEmpleado.add(jSeparator3);

        subMenuReportesEmpleado.setText("Reportes...");
        subMenuReportesEmpleado.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        itemBuscarPorId2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarPorId2.setText("Buscar por Id");
        subMenuReportesEmpleado.add(itemBuscarPorId2);

        itemBuscarPorCodigoProyecto2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarPorCodigoProyecto2.setText("Buscar por Codigo Proyecto");
        subMenuReportesEmpleado.add(itemBuscarPorCodigoProyecto2);

        menuEmpleado.add(subMenuReportesEmpleado);

        barraDeMenu.add(menuEmpleado);

        menuEmpresa.setText("Empresa");
        menuEmpresa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        itemAgregarEmpresa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemAgregarEmpresa.setText("Agregar...");
        itemAgregarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarEmpresaActionPerformed(evt);
            }
        });
        menuEmpresa.add(itemAgregarEmpresa);

        itemBuscarEmpresa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarEmpresa.setText("Buscar...");
        itemBuscarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarEmpresaActionPerformed(evt);
            }
        });
        menuEmpresa.add(itemBuscarEmpresa);

        itemEditarEmpresa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemEditarEmpresa.setText("Modificar...");
        itemEditarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarEmpresaActionPerformed(evt);
            }
        });
        menuEmpresa.add(itemEditarEmpresa);

        itemEliminarEmpresa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemEliminarEmpresa.setText("Eliminar...");
        itemEliminarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarEmpresaActionPerformed(evt);
            }
        });
        menuEmpresa.add(itemEliminarEmpresa);
        menuEmpresa.add(jSeparator4);

        subMenuReportesEmpresa.setText("Reportes...");
        subMenuReportesEmpresa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        itemBuscarPorId3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarPorId3.setText("Buscar por Id");
        subMenuReportesEmpresa.add(itemBuscarPorId3);

        itemBuscarPorCodigoProyecto3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarPorCodigoProyecto3.setText("Buscar por Codigo Proyecto");
        subMenuReportesEmpresa.add(itemBuscarPorCodigoProyecto3);

        menuEmpresa.add(subMenuReportesEmpresa);

        barraDeMenu.add(menuEmpresa);

        menuPromotor.setText("Promotor");
        menuPromotor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        itemAgregarPromotor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemAgregarPromotor.setText("Agregar...");
        itemAgregarPromotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarPromotorActionPerformed(evt);
            }
        });
        menuPromotor.add(itemAgregarPromotor);

        itemBuscarPromotor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarPromotor.setText("Buscar...");
        itemBuscarPromotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarPromotorActionPerformed(evt);
            }
        });
        menuPromotor.add(itemBuscarPromotor);

        itemEditarPromotor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemEditarPromotor.setText("Modificar...");
        itemEditarPromotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarPromotorActionPerformed(evt);
            }
        });
        menuPromotor.add(itemEditarPromotor);

        itemEliminarPromotor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemEliminarPromotor.setText("Eliminar...");
        itemEliminarPromotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarPromotorActionPerformed(evt);
            }
        });
        menuPromotor.add(itemEliminarPromotor);
        menuPromotor.add(jSeparator5);

        subMenuReportesPromotor.setText("Reportes...");
        subMenuReportesPromotor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        itemBuscarPorId4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarPorId4.setText("Buscar por Id");
        subMenuReportesPromotor.add(itemBuscarPorId4);

        itemBuscarPorCodigoProyecto4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarPorCodigoProyecto4.setText("Buscar por Codigo Proyecto");
        subMenuReportesPromotor.add(itemBuscarPorCodigoProyecto4);

        menuPromotor.add(subMenuReportesPromotor);

        barraDeMenu.add(menuPromotor);

        menuProyecto.setText("Proyecto");
        menuProyecto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        itemAgregarProyecto.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemAgregarProyecto.setText("Agregar...");
        itemAgregarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarProyectoActionPerformed(evt);
            }
        });
        menuProyecto.add(itemAgregarProyecto);

        itemBuscarProyecto.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarProyecto.setText("Buscar...");
        itemBuscarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarProyectoActionPerformed(evt);
            }
        });
        menuProyecto.add(itemBuscarProyecto);

        itemEditarProyecto.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemEditarProyecto.setText("Modificar...");
        itemEditarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarProyectoActionPerformed(evt);
            }
        });
        menuProyecto.add(itemEditarProyecto);

        itemEliminarProyecto.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemEliminarProyecto.setText("Eliminar...");
        itemEliminarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarProyectoActionPerformed(evt);
            }
        });
        menuProyecto.add(itemEliminarProyecto);
        menuProyecto.add(jSeparator1);

        subMenuReportesProyecto.setText("Reportes...");
        subMenuReportesProyecto.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        itemBuscarPorId.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarPorId.setText("Buscar por Id");
        subMenuReportesProyecto.add(itemBuscarPorId);

        itemBuscarPorCodigoProyecto.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarPorCodigoProyecto.setText("Buscar por Codigo Proyecto");
        subMenuReportesProyecto.add(itemBuscarPorCodigoProyecto);

        menuProyecto.add(subMenuReportesProyecto);

        barraDeMenu.add(menuProyecto);

        menuTarea.setText("Tarea");
        menuTarea.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        itemAgregarTarea.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemAgregarTarea.setText("Agregar...");
        itemAgregarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarTareaActionPerformed(evt);
            }
        });
        menuTarea.add(itemAgregarTarea);

        itemBuscarTarea.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarTarea.setText("Buscar...");
        itemBuscarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarTareaActionPerformed(evt);
            }
        });
        menuTarea.add(itemBuscarTarea);

        itemEditarTarea.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemEditarTarea.setText("Modificar...");
        itemEditarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarTareaActionPerformed(evt);
            }
        });
        menuTarea.add(itemEditarTarea);

        itemEliminarTarea.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemEliminarTarea.setText("Eliminar...");
        itemEliminarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarTareaActionPerformed(evt);
            }
        });
        menuTarea.add(itemEliminarTarea);
        menuTarea.add(jSeparator7);

        subMenuReportesTarea.setText("Reportes...");
        subMenuReportesTarea.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        itemBuscarPorId6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarPorId6.setText("Buscar por Id");
        subMenuReportesTarea.add(itemBuscarPorId6);

        itemBuscarPorCodigoProyecto6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarPorCodigoProyecto6.setText("Buscar por Codigo Proyecto");
        subMenuReportesTarea.add(itemBuscarPorCodigoProyecto6);

        menuTarea.add(subMenuReportesTarea);

        barraDeMenu.add(menuTarea);

        menuDocumento.setText("Documento");
        menuDocumento.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        itemAgregarDocumento.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemAgregarDocumento.setText("Agregar...");
        itemAgregarDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarDocumentoActionPerformed(evt);
            }
        });
        menuDocumento.add(itemAgregarDocumento);

        itemBuscarDocumento.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarDocumento.setText("Buscar...");
        itemBuscarDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarDocumentoActionPerformed(evt);
            }
        });
        menuDocumento.add(itemBuscarDocumento);

        itemEditarDocumento.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemEditarDocumento.setText("Modificar...");
        itemEditarDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarDocumentoActionPerformed(evt);
            }
        });
        menuDocumento.add(itemEditarDocumento);

        itemEliminarDocumento.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemEliminarDocumento.setText("Eliminar...");
        itemEliminarDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarDocumentoActionPerformed(evt);
            }
        });
        menuDocumento.add(itemEliminarDocumento);
        menuDocumento.add(jSeparator6);

        subMenuReportesDocumento.setText("Reportes...");
        subMenuReportesDocumento.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        itemBuscarPorId5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarPorId5.setText("Buscar por Id");
        subMenuReportesDocumento.add(itemBuscarPorId5);

        itemBuscarPorCodigoProyecto5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarPorCodigoProyecto5.setText("Buscar por Codigo Proyecto");
        subMenuReportesDocumento.add(itemBuscarPorCodigoProyecto5);

        menuDocumento.add(subMenuReportesDocumento);

        barraDeMenu.add(menuDocumento);

        menuVersion.setText("Version");
        menuVersion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        itemAgregarVersion.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemAgregarVersion.setText("Agregar...");
        itemAgregarVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarVersionActionPerformed(evt);
            }
        });
        menuVersion.add(itemAgregarVersion);

        itemBuscarVersion.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarVersion.setText("Buscar...");
        itemBuscarVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarVersionActionPerformed(evt);
            }
        });
        menuVersion.add(itemBuscarVersion);

        itemEditarVersion.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemEditarVersion.setText("Modificar...");
        itemEditarVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarVersionActionPerformed(evt);
            }
        });
        menuVersion.add(itemEditarVersion);

        itemEliminarVersion.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemEliminarVersion.setText("Eliminar...");
        itemEliminarVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarVersionActionPerformed(evt);
            }
        });
        menuVersion.add(itemEliminarVersion);
        menuVersion.add(jSeparator8);

        subMenuReportesVersion.setText("Reportes...");
        subMenuReportesVersion.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        itemBuscarPorId7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarPorId7.setText("Buscar por Id");
        subMenuReportesVersion.add(itemBuscarPorId7);

        itemBuscarPorCodigoProyecto7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemBuscarPorCodigoProyecto7.setText("Buscar por Codigo Proyecto");
        subMenuReportesVersion.add(itemBuscarPorCodigoProyecto7);

        menuVersion.add(subMenuReportesVersion);

        barraDeMenu.add(menuVersion);

        setJMenuBar(barraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1072, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemBuscarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarProyectoActionPerformed
        VentanaCrudProyecto ventana = new VentanaCrudProyecto(this, true);

        ventana.setTitle("Buscar Proyecto");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoNombrerClave()
                                                            ,ventana.getCampoDenomComercial()
                                                            ,ventana.getCampoEstado()
                                                            ,ventana.getCampoFechaInicio()
                                                            ,ventana.getCampoFechaFinalizacion()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemBuscarProyectoActionPerformed

    private void itemBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarUsuarioActionPerformed
        VentanaCrudUsuario ventana = new VentanaCrudUsuario(this, true);

        ventana.setTitle("Buscar Usuario");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoContrasena()
                                                            ,ventana.getCampoEstado()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemBuscarUsuarioActionPerformed

    private void itemBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarEmpleadoActionPerformed
        VentanaCrudEmpleado ventana = new VentanaCrudEmpleado(this, true);

        ventana.setTitle("Buscar Empleado");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoNombre()
                                                            ,ventana.getCampoApellido()
                                                            ,ventana.getCampoDireccion()
                                                            ,ventana.getCampoTelefono()
                                                            ,ventana.getCampoCorreoElectronico()
                                                            ,ventana.getCampoRol()
                                                            ,ventana.getCampoTipoContrato()
                                                            ,ventana.getCampoFechaContratacion()
                                                            ,ventana.getCampoFechaNacimiento()
                                                            ,ventana.getCampoArea()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemBuscarEmpleadoActionPerformed

    private void itemBuscarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarEmpresaActionPerformed
        VentanaCrudEmpresa ventana = new VentanaCrudEmpresa(this, true);

        ventana.setTitle("Buscar Empresa");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoNombre()
                                                            ,ventana.getCampoTelefono()                                                           
                                                            ,ventana.getCampoCorreoElectropnico()                                                            
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemBuscarEmpresaActionPerformed

    private void itemBuscarPromotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarPromotorActionPerformed
        VentanaCrudEmpleado ventana = new VentanaCrudEmpleado(this, true);

        ventana.setTitle("Buscar Promotor");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoNombre()
                                                            ,ventana.getCampoApellido()
                                                            ,ventana.getCampoDireccion()
                                                            ,ventana.getCampoTelefono()
                                                            ,ventana.getCampoCorreoElectronico()
                                                            ,ventana.getCampoRol()
                                                            ,ventana.getCampoTipoContrato()
                                                            ,ventana.getCampoFechaContratacion()
                                                            ,ventana.getCampoFechaNacimiento()
                                                            ,ventana.getCampoArea()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemBuscarPromotorActionPerformed

    private void itemBuscarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarDocumentoActionPerformed
        VentanaCrudDocumento ventana = new VentanaCrudDocumento(this, true);

        ventana.setTitle("Buscar Documento");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoProyecto()                                                            
                                                            ,ventana.getCampoDescripcion()
                                                            ,ventana.getCampoFecha()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemBuscarDocumentoActionPerformed

    private void itemBuscarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarTareaActionPerformed
        VentanaCrudTarea ventana = new VentanaCrudTarea(this, true);

        ventana.setTitle("Buscar Tarea");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoDescricpcion()
                                                            ,ventana.getCampoTipo()
                                                            ,ventana.getCampoDuracionEstimada()
                                                            ,ventana.getCampoDuracionReal()
                                                            ,ventana.getCampoEmpleado()
                                                            ,ventana.getCampoPrioridad()
                                                            ,ventana.getCampoFechaInicioEstimada()
                                                            ,ventana.getCampoFechaInicioReal()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemBuscarTareaActionPerformed

    private void itemBuscarVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarVersionActionPerformed
        VentanaCrudVersion ventana = new VentanaCrudVersion(this, true);

        ventana.setTitle("Buscar Versión");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoDescripcion()
                                                            ,ventana.getCampoEmpleado()
                                                            ,ventana.getCampoFecha()                                                            
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemBuscarVersionActionPerformed

    private void itemAgregarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarEmpresaActionPerformed
        
        VentanaCrudEmpresa ventana = new VentanaCrudEmpresa(this, true);
        ventana.setTitle("Agregar Empresa");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonBuscar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
        
    }//GEN-LAST:event_itemAgregarEmpresaActionPerformed

    private void itemAgregarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarDocumentoActionPerformed
        VentanaCrudDocumento ventana = new VentanaCrudDocumento(this, true);
        ventana.setTitle("Agregar Documento");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonBuscar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemAgregarDocumentoActionPerformed

    private void itemEditarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarDocumentoActionPerformed
        VentanaCrudDocumento ventana = new VentanaCrudDocumento(this, true);

        ventana.setTitle("Editar Documento");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()                                            
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoProyecto()                                                            
                                                            ,ventana.getCampoDescripcion()
                                                            ,ventana.getCampoFecha()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEditarDocumentoActionPerformed

    private void itemEliminarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarDocumentoActionPerformed
        VentanaCrudDocumento ventana = new VentanaCrudDocumento(this, true);

        ventana.setTitle("Eliminar Documento");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar()                                            
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoProyecto()                                                            
                                                            ,ventana.getCampoDescripcion()
                                                            ,ventana.getCampoFecha()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEliminarDocumentoActionPerformed

    private void itemAgregarVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarVersionActionPerformed
        VentanaCrudVersion ventana = new VentanaCrudVersion(this, true);
        ventana.setTitle("Agregar Version");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonBuscar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemAgregarVersionActionPerformed

    private void itemAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarUsuarioActionPerformed
        VentanaCrudUsuario ventana = new VentanaCrudUsuario (this, true);
        ventana.setTitle("Agregar Usuario");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonBuscar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemAgregarUsuarioActionPerformed

    private void itemEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarUsuarioActionPerformed
        VentanaCrudUsuario ventana = new VentanaCrudUsuario(this, true);

        ventana.setTitle("Editar Usuario");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()                                 
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoContrasena()
                                                            ,ventana.getCampoEstado()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEditarUsuarioActionPerformed

    private void itemEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarUsuarioActionPerformed
        VentanaCrudUsuario ventana = new VentanaCrudUsuario(this, true);

        ventana.setTitle("Eliminar Usuario");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar()                                            
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                           ventana.getCampoContrasena()
                                                           ,ventana.getCampoEstado()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEliminarUsuarioActionPerformed

    private void itemAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarEmpleadoActionPerformed
        VentanaCrudEmpleado ventana = new VentanaCrudEmpleado(this, true);
        ventana.setTitle("Agregar Empleado");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonBuscar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
        };
        
        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoArea()
                                                            
                                                            };
        campoDeSoLoLectura(campoDeText);
        desabilitarBotones(miBotones);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);        
    }//GEN-LAST:event_itemAgregarEmpleadoActionPerformed

    private void itemEditarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarEmpleadoActionPerformed
        VentanaCrudEmpleado ventana = new VentanaCrudEmpleado(this, true);

        ventana.setTitle("Editar Empleado");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()                                            
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoNombre()
                                                            ,ventana.getCampoApellido()
                                                            ,ventana.getCampoDireccion()
                                                            ,ventana.getCampoTelefono()
                                                            ,ventana.getCampoCorreoElectronico()
                                                            ,ventana.getCampoRol()
                                                            ,ventana.getCampoTipoContrato()
                                                            ,ventana.getCampoFechaContratacion()
                                                            ,ventana.getCampoFechaNacimiento()
                                                            ,ventana.getCampoArea()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEditarEmpleadoActionPerformed

    private void itemEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarEmpleadoActionPerformed
        VentanaCrudEmpleado ventana = new VentanaCrudEmpleado(this, true);

        ventana.setTitle("Eliminar Empleado");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar()                                            
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoNombre()
                                                            ,ventana.getCampoApellido()
                                                            ,ventana.getCampoDireccion()
                                                            ,ventana.getCampoTelefono()
                                                            ,ventana.getCampoCorreoElectronico()
                                                            ,ventana.getCampoRol()
                                                            ,ventana.getCampoTipoContrato()
                                                            ,ventana.getCampoFechaContratacion()
                                                            ,ventana.getCampoFechaNacimiento()
                                                            ,ventana.getCampoArea()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEliminarEmpleadoActionPerformed

    private void itemEditarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarEmpresaActionPerformed
        VentanaCrudEmpresa ventana = new VentanaCrudEmpresa(this, true);

        ventana.setTitle("Editar Empresa");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()                                            
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoNombre()
                                                            ,ventana.getCampoTelefono()                                                           
                                                            ,ventana.getCampoCorreoElectropnico()                                                            
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEditarEmpresaActionPerformed

    private void itemEliminarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarEmpresaActionPerformed
        VentanaCrudEmpresa ventana = new VentanaCrudEmpresa(this, true);

        ventana.setTitle("Eliminar Empresa");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar()
                                            
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoNombre()
                                                            ,ventana.getCampoTelefono()                                                           
                                                            ,ventana.getCampoCorreoElectropnico()                                                            
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEliminarEmpresaActionPerformed

    private void itemAgregarPromotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarPromotorActionPerformed
        VentanaCrudEmpleado ventana = new VentanaCrudEmpleado(this, true);
        ventana.setTitle("Agregar Promotor");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonBuscar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemAgregarPromotorActionPerformed

    private void itemEditarPromotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarPromotorActionPerformed
        VentanaCrudEmpleado ventana = new VentanaCrudEmpleado(this, true);

        ventana.setTitle("Editar Documento");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()                                            
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoNombre()
                                                            ,ventana.getCampoApellido()
                                                            ,ventana.getCampoDireccion()
                                                            ,ventana.getCampoTelefono()
                                                            ,ventana.getCampoCorreoElectronico()
                                                            ,ventana.getCampoRol()
                                                            ,ventana.getCampoTipoContrato()
                                                            ,ventana.getCampoFechaContratacion()
                                                            ,ventana.getCampoFechaNacimiento()
                                                            ,ventana.getCampoArea()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEditarPromotorActionPerformed

    private void itemAgregarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarProyectoActionPerformed
        VentanaCrudProyecto ventana = new VentanaCrudProyecto(this, true);
        ventana.setTitle("Agregar Proyecto");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonBuscar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemAgregarProyectoActionPerformed

    private void itemEditarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarProyectoActionPerformed
        VentanaCrudProyecto ventana = new VentanaCrudProyecto(this, true);

        ventana.setTitle("Editar Proyecto");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()                                            
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoNombrerClave()
                                                            ,ventana.getCampoDenomComercial()
                                                            ,ventana.getCampoEstado()
                                                            ,ventana.getCampoFechaInicio()
                                                            ,ventana.getCampoFechaFinalizacion()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEditarProyectoActionPerformed

    private void itemEliminarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarProyectoActionPerformed
        VentanaCrudProyecto ventana = new VentanaCrudProyecto(this, true);

        ventana.setTitle("Eliminar Proyecto");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar()                                            
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoNombrerClave()
                                                            ,ventana.getCampoDenomComercial()
                                                            ,ventana.getCampoEstado()
                                                            ,ventana.getCampoFechaInicio()
                                                            ,ventana.getCampoFechaFinalizacion()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEliminarProyectoActionPerformed

    private void itemAgregarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarTareaActionPerformed
        VentanaCrudTarea ventana = new VentanaCrudTarea(this, true);
        ventana.setTitle("Agregar Tarea");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonBuscar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemAgregarTareaActionPerformed

    private void itemEditarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarTareaActionPerformed
        VentanaCrudTarea ventana = new VentanaCrudTarea(this, true);

        ventana.setTitle("Editar Tarea");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()                                            
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoDescricpcion()
                                                            ,ventana.getCampoTipo()
                                                            ,ventana.getCampoDuracionEstimada()
                                                            ,ventana.getCampoDuracionReal()
                                                            ,ventana.getCampoEmpleado()
                                                            ,ventana.getCampoPrioridad()
                                                            ,ventana.getCampoFechaInicioEstimada()
                                                            ,ventana.getCampoFechaInicioReal()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEditarTareaActionPerformed

    private void itemEliminarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarTareaActionPerformed
        VentanaCrudTarea ventana = new VentanaCrudTarea(this, true);

        ventana.setTitle("Eliminar Tarea");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar()                                            
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoDescricpcion()
                                                            ,ventana.getCampoTipo()
                                                            ,ventana.getCampoDuracionEstimada()
                                                            ,ventana.getCampoDuracionReal()
                                                            ,ventana.getCampoEmpleado()
                                                            ,ventana.getCampoPrioridad()
                                                            ,ventana.getCampoFechaInicioEstimada()
                                                            ,ventana.getCampoFechaInicioReal()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEliminarTareaActionPerformed

    private void itemEditarVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarVersionActionPerformed
        VentanaCrudVersion ventana = new VentanaCrudVersion(this, true);

        ventana.setTitle("Editar Versión");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()                                           
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoDescripcion()
                                                            ,ventana.getCampoEmpleado()
                                                            ,ventana.getCampoFecha()                                                            
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEditarVersionActionPerformed

    private void itemEliminarVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarVersionActionPerformed
        VentanaCrudVersion ventana = new VentanaCrudVersion(this, true);

        ventana.setTitle("Eliminar Versión");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar()                                            
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoDescripcion()
                                                            ,ventana.getCampoEmpleado()
                                                            ,ventana.getCampoFecha()                                                            
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEliminarVersionActionPerformed

    private void itemEliminarPromotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarPromotorActionPerformed
        VentanaCrudEmpleado ventana = new VentanaCrudEmpleado(this, true);

        ventana.setTitle("Eliminar Promotor");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar()                                            
        };
        desabilitarBotones(miBotones);

        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoNombre()
                                                            ,ventana.getCampoApellido()
                                                            ,ventana.getCampoDireccion()
                                                            ,ventana.getCampoTelefono()
                                                            ,ventana.getCampoCorreoElectronico()
                                                            ,ventana.getCampoRol()
                                                            ,ventana.getCampoTipoContrato()
                                                            ,ventana.getCampoFechaContratacion()
                                                            ,ventana.getCampoFechaNacimiento()
                                                            ,ventana.getCampoArea()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEliminarPromotorActionPerformed

    public void desabilitarBotones(JButton botones[]){
        for(JButton boton: botones){
            boton.setEnabled(false);
        }
    }

    public void campoDeSoLoLectura(JTextComponent campoTexto[]){
        for (JTextComponent component : campoTexto) {
            component.setEditable(false);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraDeMenu;
    private javax.swing.JMenuItem itemAgregarDocumento;
    private javax.swing.JMenuItem itemAgregarEmpleado;
    private javax.swing.JMenuItem itemAgregarEmpresa;
    private javax.swing.JMenuItem itemAgregarPromotor;
    private javax.swing.JMenuItem itemAgregarProyecto;
    private javax.swing.JMenuItem itemAgregarTarea;
    private javax.swing.JMenuItem itemAgregarUsuario;
    private javax.swing.JMenuItem itemAgregarVersion;
    private javax.swing.JMenuItem itemBuscarDocumento;
    private javax.swing.JMenuItem itemBuscarEmpleado;
    private javax.swing.JMenuItem itemBuscarEmpresa;
    private javax.swing.JMenuItem itemBuscarPorCodigoProyecto;
    private javax.swing.JMenuItem itemBuscarPorCodigoProyecto1;
    private javax.swing.JMenuItem itemBuscarPorCodigoProyecto2;
    private javax.swing.JMenuItem itemBuscarPorCodigoProyecto3;
    private javax.swing.JMenuItem itemBuscarPorCodigoProyecto4;
    private javax.swing.JMenuItem itemBuscarPorCodigoProyecto5;
    private javax.swing.JMenuItem itemBuscarPorCodigoProyecto6;
    private javax.swing.JMenuItem itemBuscarPorCodigoProyecto7;
    private javax.swing.JMenuItem itemBuscarPorId;
    private javax.swing.JMenuItem itemBuscarPorId1;
    private javax.swing.JMenuItem itemBuscarPorId2;
    private javax.swing.JMenuItem itemBuscarPorId3;
    private javax.swing.JMenuItem itemBuscarPorId4;
    private javax.swing.JMenuItem itemBuscarPorId5;
    private javax.swing.JMenuItem itemBuscarPorId6;
    private javax.swing.JMenuItem itemBuscarPorId7;
    private javax.swing.JMenuItem itemBuscarPromotor;
    private javax.swing.JMenuItem itemBuscarProyecto;
    private javax.swing.JMenuItem itemBuscarTarea;
    private javax.swing.JMenuItem itemBuscarUsuario;
    private javax.swing.JMenuItem itemBuscarVersion;
    private javax.swing.JMenuItem itemCambiarClaveUsuario;
    private javax.swing.JMenuItem itemEditarDocumento;
    private javax.swing.JMenuItem itemEditarEmpleado;
    private javax.swing.JMenuItem itemEditarEmpresa;
    private javax.swing.JMenuItem itemEditarPromotor;
    private javax.swing.JMenuItem itemEditarProyecto;
    private javax.swing.JMenuItem itemEditarTarea;
    private javax.swing.JMenuItem itemEditarUsuario;
    private javax.swing.JMenuItem itemEditarVersion;
    private javax.swing.JMenuItem itemEliminarDocumento;
    private javax.swing.JMenuItem itemEliminarEmpleado;
    private javax.swing.JMenuItem itemEliminarEmpresa;
    private javax.swing.JMenuItem itemEliminarPromotor;
    private javax.swing.JMenuItem itemEliminarProyecto;
    private javax.swing.JMenuItem itemEliminarTarea;
    private javax.swing.JMenuItem itemEliminarUsuario;
    private javax.swing.JMenuItem itemEliminarVersion;
    private javax.swing.JMenuItem itemRecordarClaveUsuario;
    private javax.swing.JMenuItem itemSalirUsuario;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenu menuDocumento;
    private javax.swing.JMenu menuEmpleado;
    private javax.swing.JMenu menuEmpresa;
    private javax.swing.JMenu menuPromotor;
    private javax.swing.JMenu menuProyecto;
    private javax.swing.JMenu menuTarea;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenu menuVersion;
    private javax.swing.JMenu subMenuReportesDocumento;
    private javax.swing.JMenu subMenuReportesEmpleado;
    private javax.swing.JMenu subMenuReportesEmpresa;
    private javax.swing.JMenu subMenuReportesPromotor;
    private javax.swing.JMenu subMenuReportesProyecto;
    private javax.swing.JMenu subMenuReportesTarea;
    private javax.swing.JMenu subMenuReportesUsuario;
    private javax.swing.JMenu subMenuReportesVersion;
    // End of variables declaration//GEN-END:variables
}
